Fix support for multiple generated sprites in local
jeparlefrancais/tarmac pull request #5
Opened 2021-03-17 10:03 UTC by Vorlias

If tarmac generates multiple spritesheets, they would overwrite previous spritesheets with `--target local` due to having the same sprite names (`spritesheet`). 

This addresses that and suffixes each spritesheet with a number that's incremented per spritesheet.

E.g. two spritesheets -> `spritesheet-1`, `spritesheet-2`.

2021-04-15 03:17 UTC, jeparlefrancais commented
Hey! Sorry I need to check my notification settings, I didn't even know you submitted a PR 😬 Thanks for your contribution it's awesome!

That seems like a reasonable fix! Can you run rustfmt so that CI checks are green? You can run `cargo fmt` and it should fix it.

Again, sorry the delay! Next time ping me on discord if I don't reply a few days

2021-04-17 03:15 UTC, Vorlias commented
Alright I think it's good now.

2021-04-17 03:22 UTC, jeparlefrancais requested changes

2021-04-17 03:22 UTC, jeparlefrancais commented on src/commands/sync.rs
> -            alpha_bleed(&mut packed_image.img);
Hum could this be a bad merge issue? This was added in the last PR

2021-07-15 01:09 UTC, Vorlias commented
I'm not sure how that vanished, should be fixed now. Apologies for the _very late_ response. Been quite busy.

2022-09-10 05:44 UTC, closed without merging